using System.Security.Cryptography;


namespace Uber.DemoTools
{
    public static class Quotes
    {
        public static string GetRandomQuote()
        {
            var generator = RNGCryptoServiceProvider.Create();
            var bytes = new byte[1];
            generator.GetBytes(bytes);
            var index = (int)bytes[0] % _quotes.Length;

            return _quotes[index];
        }

        private static string[] _quotes = new string[]
        {
            "chakled litel boll (c) v3nom",
            "so drinked (c) Rizla-",
            "id rather eat ur mothers shit after shes been on a shit diet for a month (c) pcb",
            "there was a quato related james bond (c) TheDynamite",
            "this frag was sponsored by luck (c) Ultrameta",
            "neither of you take one frag from me in a duel (c) Spetz",
            "you peace of shit take other model (c) QiGonG",
            "u only got one router in your country? (c) ilu",
            "hi im myt, half of my keyboard is binded to pcb quotes (c) pcb",
            "tdm is all about poland and cpm27 (c) aab",
            "ye i finally got my own quote (c) damn-",
            "i dont need your help making me look like an idiot (c) pcb",
            "why hi ban me i ask sub:( (c) bullet",
            "WAXEDDDDDDDDDDDDDDDDDDDD (c) pejnisson",
            "PAYJETIC TEAM (c) Falko",
            "DOODR, 1SEX (c) xero",
            "niceninciencienceinceinceicnnice (c) DDK",
            "in my village, man and woman looks the same (c) mih",
            "i was born to def (c) TheDynamite",
            "ill send you a mold of my ass (c) pcb",
            "im danish im born like that (c) pcb",
            "how not to rage if you can see chernobyl from your window (c) vicek",
            "fuck me up (c) Pushpabon",
            "cant talking with pll like u (c) olszanek",
            "thank god you dont quote me (c) guh4rd",
            "get the fuck on with it (c) mistralol",
            "don't funny (c) lennox",
            "sorry, my englich is easy (c) waitze",
            "im riding the dog (c) pcb",
            "AGHAGHAGHAGHAGHAGHAGHAGAHGAHGA (c) AHXNXA",
            "i thought norz n nzro were 2 diff ppl (c) pcb",
            "!add TDM (c) Pushpabon",
            "cpma the modern man's chess (c) panic",
            "i am a total moron (c) sanchi",
            "im good now cause i changed model and shit (c) panic",
            "let me think (c) panic",
            "fuyck foff (c) astro",
            "sry i can play (c) Rizla-",
            "ethad is the son of ozzy osbourne (c) Rizla-",
            "Well I shared some of my kugelns with them:P (c) Terifire",
            "ugh I'm going to bad sorry man :< (c) Terifire",
            "FYCJ IU CANT TYPE (c) Terifire",
            "maybe I can drink my shaft sorrows away (c) Terifire",
            "And people would someone get passed the password screen and snoop around on my computer. (c) Terifire",
            "In the last month I have produced so much luck I could shit a leprechaun (c) Terifire",
            "no I'm trying to create an nmap script so I can brute force a porn site's http auth (c) Terifire",
            "man brute-forcing ironically is not the best way to retrieve porn site passwords (c) Terifire",
            "He's getting a load of my shaft for christmas (c) Terifire",
            "im gonna make so many airrockets nasa will declare bankrupcytsty (c) ovol1ty",
            "rest gonna be cuted (c) gogetto",
            "can i watch you doing it ? (c) gogetto",
            "you make have grown your own fingers.. but sometimes you need to curse them and threaten them.. whatevah God do what he want (c) nerfquark",
            "i so fucking rape with below 80 ping (c) Raist",
            "I ate so much I move like a VQ3er :/ (c) myT",
            "i men (c) gog",
            "Christiaan: just came with me? (c) gog",
            "when i was kid i thought that in the past everything was black and white, because old movies were black and white lol :P (c) gog",
            "myT I am impress with your shaft (c) Terifire",
            "I'm moving around like a pregnant donkey (c) Terifire",
            "what happened when you waxed the shit out of everyone (c) gaiia",
            "lucky piece of cuntjuice (c) gaiia",
            "and burb, because beer (c) JackBender",
            "I don't usually quote myself, but the opportunity was compelling (c) JackBender",
            "it's not you that I'm supposed to feel man. (c) Terifire",
            "Aparently I'm slowed than that TDM game :( (c) Terifire",
            "I would never use the word shaft in such a blasphemous manner. (c) Terifire",
            "one day raist, I will have a bigger cunt than you (c) Terifire",
            "myT I'd give my left testicle for your rocket aim (c) Terifire",
            "myt is so pro he dodges sg (c) ahxnxa",
            "if I was a superhero my power would be to pick morans (c) gaiia",
            "I enjoyed a bit of domination (c) Memento_Mori",
            "cant lay down coz my room spins (c) mih",
            "he also wrote, diana has told her cookee that charls transform into a reptile when she has menstruation, cause he smelled her blood. (c) HellTiger",
            "whats the assword (c) Rain-",
            "alles-tu faire foutre (c) jihnsius",
            "yaeh okay cunt you hack (c) raiseq3",
            "I'm not the only stupid person (c) Terifire",
            "aparently, listening to music does not make your farts silent :( (c) Terifire",
            "myT created a bfg hack (c) Hehateme1",
            "i sweat to fuck (c) lsv",
            "im gonna cock some noodles (c) erhiy",
            "i dont quit (c) ZEN|ele",
            "life sometimes is like somthing of once potato (c) 2pu",
            "It's like angry birds where I'm the bird (c) ZeriouS",
            "If I had 50% of your LG aim I'd never switch weapon (c) lipz",
            "some players ntf play cast chienese map ? :p (c) nTk",
            "a man who pooped in the barbecue has to salt his wifes hair (c) HellTiger",
            "Do you even shaftlift, bro? (c) myT",
            "I successfully failed at everything. (c) myT",
            "myt show me cool jumps (c) simmarine",
            "being in this channel makes my lg 10% stronger (c) Hehateme",
            "I'm feeling eaty (c) es",
            "myT you're so hard to hit, you're like Houdini in the night. (c) Gomo",
            "myt your settings are bullshit (c) dys-",
            "I don't have a lot of wisdom (c) erhiy",
            "I can't play right now, I'm on the internet. (c) gramz",
            "I might have to connect to my internet right now. (c) Gomo",
            "Can we start this game so I can start losing? (c) tupu",
            "i think myt making the finals proves hacks (c) Kwong-Lo",
            "anything myT is fun (c) Hehateme",
            "pure misscomincation (c) Anarrr",
            "you cant out tdm myT (c) bronze",
            "demos are didnt hapen (c) Monty",
            "to make the cow angry. u don't the cow to be angry (c) Monty",
            "had to watch it with r_showtits (c) santile",
            "someone call the lg abuse hotline (c) HyDr0",
            "That shaft is sublime (c) Terifire",
            "I would keep it in an underwear (c) es",
            "fucking aerowalk (c) memphis",
            "fuck everything except myT (c) Bjarke",
            "this map has my 2 least favorite things: lava and myT (c) bronze",
            "grate game (c) supercruel",
            "i know i dunno (c) gogetto",
            "and now i god (c) gogetto",
            "im sick of your mega luck (c) Nzr0",
            "proof me wrong (c) raeg",
            "dunno i always had a soft hard for ca (c) Raist",
            "ass much as i care abaut you (c) brithey",
            "cOwabanga <3 (c) mih8r",
            "I like run run run! And stuff like that. (c) cooller",
            "le lightsaber, terriiiiiiiiiible (c) Rizla-",
            "I have no life. (c) eThaD",
            "My dick is untouched. (c) black",
            "the cam is now how it turns sideways as it gets close to the corpse (c) Naper",
            "so drinked (c) Rizla-",
            "in my village, man and woman looks the same (c) mih",
            "AGHAGHAGHAGHAGHAGHAGHAGAHGAHGA (c) AHXNXA",
            "i was born to def (c) TheDynamite",
            "hands too cold to rail (c) Spetz",
            "Going to macdonalds for a salad is like going to hug a whore with aids. (c) shadow"
        };
    }
}